---
- hosts: windows_client

  vars:
    # workaround backslash+quote parsing bug
    backslash: \

  tasks:
    - include_tasks: tasks/prepare.yml
    - include_tasks: tasks/policies.yml
    - include_tasks: tasks/misc.yml
    - include_tasks: tasks/disable-defender.yml
      when: disable_defender
    - include_tasks: tasks/software.yml
      when: install_software
    - include_tasks: tasks/cleanup.yml
