---
- name: Remove all Event Viewer entries
  when: cleanup
  win_shell: |
    Get-EventLog -List | ForEach-Object {$_.Log} | ForEach-Object {Clear-EventLog -LogName $_ }

- name: Remove all temporary files
  when: cleanup
  win_shell: |
    Remove-Item "{{ ansible_env.TEMP }}\*" -Recurse -Force
    Remove-Item "{{ ansible_env.SystemRoot }}\Temp\*" -Recurse -Force
    $true

- name: Clean Powershell history
  when: cleanup
  win_shell: |
    Clear-History
    Remove-Item (Get-PSReadlineOption).HistorySavePath -ErrorAction SilentlyContinue
    $true

- name: Drop WinRM disable script
  vars:
    src_file: "../DisableWinRM.ps1"
    dest_file: "{{ ansible_env.HOMEPATH }}\\Desktop\\DisableWinRM.ps1"
  win_copy:
    src: "{{ src_file }}"
    dest: "{{ dest_file }}"
    force: no
