---
- name: Temporarily disable Windows Defender
  win_shell: |
    Set-MpPreference -DisableRealtimeMonitoring $true -ErrorAction SilentlyContinue
    Set-MpPreference -DisableBehaviorMonitoring $true -ErrorAction SilentlyContinue
    Set-MpPreference -SubmitSamplesConsent NeverSend -ErrorAction SilentlyContinue
    Set-MpPreference -MAPSReporting Disabled -ErrorAction SilentlyContinue
    $true

- name: Check if changes were applied
  win_shell: >
    ((Get-MpPreference).DisableRealtimeMonitoring -eq $true)
    -and
    ((Get-MpPreference).DisableBehaviorMonitoring -eq $true)
    -and
    ((Get-MpPreference).SubmitSamplesConsent -eq 2)
    -and
    ((Get-MpPreference).MAPSReporting -eq 0)
  register: disable_defender_result

- name: Throw if changes were not applied
  fail:
    msg: Windows Defender could not be modified. Is Tamper Protection turned off?
  when: (disable_defender_result.stdout | trim) != "True"

- name: Disable Windows Defender services
  vars:
    command: >
      "wscsvc", "SecurityHealthService", "Sense", "WdBoot", "WdFilter", "WdNisDrv", "WdNisSvc", "WinDefend"
      | %{ Stop-Service $_; Set-Service $_ -StartupType Disabled }
  block:
    - vars:
        exec_args: powershell -EncodedCommand {{ command | b64encode(encoding='utf-16-le') }}
      include_tasks: util/sudo.yml

- name: Apply Defender Group Policies
  vars:
    apply_src_policy: ../res/policies/defender.txt
  include_tasks: util/apply-policies.yml
