---
- name: Modify Windows Defender to check if Tamper protection is on
  win_shell: |
    Set-MpPreference -DisableRealtimeMonitoring $true -ErrorAction SilentlyContinue
    $true

- name: Check if change was applied
  win_shell: >
    (Get-MpPreference).DisableRealtimeMonitoring -eq $true
  register: disable_defender_result

- name: Throw if change was not applied
  fail:
    msg: Windows Defender could not be modified. Is Tamper Protection turned off?
  when: (disable_defender_result.stdout | trim) != "True"

- name: Apply Defender Group Policies
  vars:
    apply_src_policy: ../res/policies/defender.txt
  include_tasks: util/apply-policies.yml
