---
- name: Disable Windows Defender
  vars:
    # https://github.com/jbara2002/windows-defender-remover
    defender_src: ../res/defender/
    defender_dest: "{{ ansible_env.TEMP }}\\defender"
  block:
    - name: Copy files
      win_copy:
        src: "{{ defender_src }}"
        dest: "{{ defender_dest }}"
        force: no
    - vars:
        command: |
          $regFiles = Get-ChildItem "{{ ansible_env.TEMP }}\\defender\\*.reg"
          foreach ($file in $regFiles) {
            reg import "$file"
          }
        exec_args: powershell.exe -EncodedCommand {{ command | b64encode(encoding='utf-16-le') }}
      include_tasks: util/sudo.yml
    - name: Cleanup
      win_file:
        path: "{{ defender_dest }}"
        state: absent

- name: Apply Defender Group Policies
  vars:
    apply_src_policy: ../res/policies/defender.txt
  include_tasks: util/apply-policies.yml
