---
- name: Disable Windows Defender
  vars:
    command: |
      Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows Defender\Features" -Name MpPlatformKillbitsFromEngine -Value ([byte[]](00,00,00,00,00,00,00,00))
      Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows Defender\Features" -Name TamperProtectionSource -Value 0
      Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows Defender\Features" -Name MpCapability -Value ([byte[]](00,00,00,00,00,00,00,00))
      Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows Defender\Features" -Name TamperProtection -Value 0
      $services = @("Sense", "WdBoot", "WdFilter", "WdNisDrv", "WdNisSvc", "WinDefend", "MsSecCore", "SgrmAgent", "SgrmBroker", "webthreatdefsvc", "webthreatdefusersvc")
      foreach ($service in $services) {
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\$service" -Name Start -Value 4
      }
    exec_args: powershell.exe -EncodedCommand {{ command | b64encode(encoding='utf-16-le') }}
  include_tasks: util/sudo.yml

- name: Apply Defender Group Policies
  vars:
    apply_src_policy: ../res/policies/defender.txt
  include_tasks: util/apply-policies.yml
