---
- name: Disable animations
  vars:
    run_script: ../res/DisableAnimations.ps1
  include_tasks: util/run-interactive.yml

- name: Set power plan to High Performance
  win_power_plan:
    name: high performance
  when: set_powerplan

- name: Disable screen timeout
  win_shell: powercfg -change -monitor-timeout-ac 0
  when: set_powerplan

- name: Disable telemetry
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\{{ item }}
    name: Debugger
    data: systray.exe
    type: string
  loop:
    - compattelrunner.exe
    - wsqmcons.exe

- name: Uninstall OneDrive
  win_shell: |
    $process = Get-Process onedrive -ErrorAction SilentlyContinue
    if ($null -ne $process) {
      $process | Stop-Process -Force
      Start-Process "$env:SystemRoot\SysWOW64\OneDriveSetup.exe" "/uninstall" -Wait
    }
    $true

- name: Uninstall built-in apps
  win_shell: |
    Get-AppxPackage *3dviewer* | Remove-AppxPackage
    Get-AppxPackage *feedback* | Remove-AppxPackage
    Get-AppxPackage *windowsmaps* | Remove-AppxPackage
    Get-AppxPackage *solitairecollection* | Remove-AppxPackage
    Get-AppxPackage *mixedreality* | Remove-AppxPackage
    Get-AppxPackage *officehub* | Remove-AppxPackage
    Get-AppxPackage *onenote* | Remove-AppxPackage
    Get-AppxPackage *mspaint* | Remove-AppxPackage # Paint 3D
    Get-AppxPackage *skypeapp* | Remove-AppxPackage
    Get-AppxPackage *screensketch* | Remove-AppxPackage
    Get-AppxPackage *getstarted* | Remove-AppxPackage # tips
    Get-AppxPackage *bingweather* | Remove-AppxPackage
    Get-AppxPackage *xbox* | Remove-AppxPackage
    $true

- name: Disable Sticky Keys
  win_regedit:
    path: HKCU:\Control Panel\Accessibility\{{ item.path }}
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: string
  loop:
    - { path: StickyKeys, name: Flags, data: 506 }
    - { path: Keyboard Response, name: Flags, data: 122 }
    - { path: ToggleKeys, name: Flags, data: 58 }

- name: Configure Windows Explorer
  win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: dword
  loop:
    - { name: Hidden, data: 1 }
    - { name: HideFileExt, data: 0 }
    - { name: HideDrivesWithNoMedia, data: 0 }
    - { name: DisallowShaking, data: 1 }
    - { name: LaunchTo, data: 1 }

- name: Disable Start Menu app suggestions
  win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: dword
  loop:
    - { name: SubscribedContent-338388Enabled, data: 0 }

- name: Delete live tiles
  vars:
    run_script: ../res/DeleteLiveTiles.ps1
  include_tasks: util/run-interactive.yml

- name: Disable spy domains via hosts file
  when: set_spy_block_hosts
  vars:
    src_dir: "/tmp/windows-vm-ansible/"
    dest_dir: "{{ ansible_env.TEMP }}\\windows-vm-ansible"
    dest_dir_remote: "$env:TEMP\\windows-vm-ansible"
  block:
    - name: Make local directory
      file:
        path: "{{ src_dir }}"
        state: directory
      delegate_to: 127.0.0.1

    - name: Download files
      get_url:
        url: "{{ item.url }}"
        dest: "{{ src_dir }}/{{ item.name }}"
      loop:
        - {
            name: spy.txt,
            url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt,
          }
        - {
            name: spy_v6.txt,
            url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy_v6.txt,
          }
      delegate_to: 127.0.0.1

    - name: Copy files
      win_copy:
        src: "{{ src_dir }}"
        dest: "{{ dest_dir }}"
        force: yes

    - name: Add files to host file
      win_shell: |
        $PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'
        Get-ChildItem "{{ dest_dir_remote }}" | Foreach-Object {
          "" >> "{{ ansible_env.SystemRoot }}\System32\drivers\etc\hosts"
          Get-Content $_.FullName >> "{{ ansible_env.SystemRoot }}\System32\drivers\etc\hosts"
        }

    - name: Cleanup remote
      win_file:
        path: "{{ dest_dir }}"
        state: absent

    - name: Cleanup local
      file:
        path: "{{ src_dir }}"
        state: absent
      delegate_to: 127.0.0.1

    - name: Set third-party NCSI
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet
        name: "{{ item.name }}"
        data: "{{ item.data }}"
        type: string
      loop:
        - { name: ActiveWebProbeContent, data: "success\n" }
        - { name: ActiveWebProbeContentV6, data: "success\n" }
        - { name: ActiveWebProbeHost, data: detectportal.firefox.com }
        - { name: ActiveWebProbeHostV6, data: detectportal.firefox.com }
        - { name: ActiveWebProbePath, data: / }
        - { name: ActiveWebProbePathV6, data: / }
