---
- name: Apply Privacy Policies
  vars:
    apply_src_policy: ../res/policies/privacy.txt
  include_tasks: util/apply-policies.yml

- name: Apply Security Policies
  vars:
    apply_src_policy: ../res/policies/security.txt
  include_tasks: util/apply-policies.yml

- name: Apply Update Policies
  vars:
    apply_src_policy: ../res/policies/updates.txt
  include_tasks: util/apply-policies.yml

- name: Apply Hardcore Policies
  when: set_hardcore_policies
  vars:
    apply_src_policy: ../res/policies/updates.txt
  include_tasks: util/apply-policies.yml
