---
- name: Apply Privacy Policies
  vars:
    apply_src_policy: ../res/policies/privacy.txt
  include_tasks: util/apply-policies.yml

- name: Block 'Use this account everywhere on your device'
  # https://docs.microsoft.com/en-us/azure/active-directory/devices/hybrid-azuread-join-plan#review-things-you-should-know
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\WorkplaceJoin
    name: BlockAADWorkplaceJoin
    data: "1"
    type: dword

- name: Apply Security Policies
  vars:
    apply_src_policy: ../res/policies/security.txt
  include_tasks: util/apply-policies.yml

- name: Apply Update Policies
  vars:
    apply_src_policy: ../res/policies/updates.txt
  include_tasks: util/apply-policies.yml

- name: Apply Hardcore Policies
  when: set_hardcore_policies
  vars:
    apply_src_policy: ../res/policies/updates.txt
  include_tasks: util/apply-policies.yml

- name: Apply Lenovo Policies
  when: set_lenovo_policies
  vars:
    apply_src_policy: ../res/policies/updates.txt
  include_tasks: util/apply-policies.yml

- name: Remove "Lenovo Fn and function keys" driver to apply blocking policy
  when: set_lenovo_policies
  win_shell: |
    $wmiObject = Get-WmiObject Win32_PnPSignedDriver | Where-Object HardWareID -eq "ACPI\VEN_LHK&DEV_2019"
    pnputil.exe /remove-device $wmiObject.DeviceID /subtree
    pnputil.exe /delete-driver $wmiObject.InfName /uninstall
