---
- name: Apply Privacy Group Policies
  vars:
    apply_src_policy: ../res/policies/privacy.txt
  include_tasks: util/apply-policies.yml

- name: Apply Security Group Policies
  vars:
    apply_src_policy: ../res/policies/security.txt
  include_tasks: util/apply-policies.yml

- name: Apply Updates Group Policies
  when: set_update_policies
  vars:
    apply_src_policy: ../res/policies/updates.txt
  include_tasks: util/apply-policies.yml
