---
# WinRM runs in non-interactive session which prevents certain functionality
# To work around this, use the task scheduler which will run in the current user's interactive session
- name: Execute interactive task
  vars:
    # run_script: ScriptFileToRun.ps1
    # run_args: Script args (defaualt: none)
    run_dest_file: "{{ ansible_env.USERPROFILE }}\\TempScript.ps1"
  block:
    - name: Copy script
      win_copy:
        src: "../{{ run_script }}"
        dest: "{{ run_dest_file }}"

    - name: Run script
      vars:
        exec_args: >-
          -ExecutionPolicy Bypass -WindowStyle Hidden
          -File "{{ run_dest_file }}" {{ run_args | default('') }}
      include_tasks: exec-interactive.yml

    - name: Clean up script
      win_file:
        path: "{{ run_dest_file }}"
        state: absent
