---
- name: Run task
  vars:
    # run_script: ScriptFileToRun.ps1
    # run_args: Script args
    run_dest_path: "{{ ansible_env.USERPROFILE }}\\TempScript.ps1"
  block:
    - name: Copy script
      win_copy:
        src: "../{{ run_script }}"
        dest: "{{ run_dest_path }}"

    - name: Run script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File "{{ run_dest_path }}" "{{ run_args | default('') }}"

    - name: Clean up script
      win_file:
        path: "{{ run_dest_path }}"
        state: absent
